sudo: required
language: python
python:
  - "3.5"
install:
  - bash scripts/install_dependencies.sh
script:
  - bash scripts/lint.sh
  - bash scripts/run_all_environments.sh
  - python src/run_atari_ppo.py --max_timesteps=1
