language: python
python:
  - "3.5"
install:
  - pip install pylint
  - pip install -r requirements.txt
  - pip install tensorflow
script:
  - PYTHONPATH=src pylint --disable=locally-disabled,fixme src
  - python src/capture_pong_play.py --savefile temp.h5 --maxsteps 1 --maxproc 1
